### PR TITLE
rocket: avoid LinkedHashMap.keys to preserve traversal order

### PR DESCRIPTION
**Pull request by hcook**
Don't trust LinkedHashMap.keys.map to provide a consistent order of traversal across module instantiations.

Even though the documentation says:
"The iterator and all traversal methods of this class visit elements in the order they were inserted."

...Scala!

### CODE REVIEW

**Comment by jackkoenig** [comment]
[I feel your pain on this one](https://github.com/ucb-bar/firrtl/pull/303) 👎

**Comment by sdtwigg** [comment]
Ew, so I looked into this and it looks like there is already a Scala issue filed on it (and potentially slated to be fixed in the far-away 2.13 release)

https://issues.scala-lang.org/browse/SI-9594

**Comment by sdtwigg** [comment]
PS: It should still be safe as long as you are calling just map, flatMap, filter, etc. (or in a for-comprehension).

**Comment by aswaterman** [comment]
Yeah, our workaround was to map over the whole map, rather than just over the keys.

**Pull request merged**
