### PR TITLE
TL2 take-over of the L1

### PR DESCRIPTION
**Pull request by terpstra**
This PR injects TL2 into the tile and L1 data caches. A TL2 Broadcast hub is use to provide multi-core coherence between data caches (passes TraceGen WMO). A streamlined config library is adopted in place of cde. Icaches and RoCCs are still using TL1 behind a tilelink2.Legacy adapter.

Known API-breaking changes:
- No more BuildTiles or common Tile base class/IO. Make a custom Tile for your core, then make a Coreplex mix-in that adds some number of instances of the new Tile.
- package cde is being retired in favor of package config. Their Parameters and Config classes are API compatible but you must change the import (config offers improved functionality for Parameters and Config, but removes Knobs and Constraints). 

Known functionality regressions:
- No AXI pbus mastering (#437) -- will fix next week.
- No more cde.Knob, cde.Constraint, or cde.World -- will not fix.
- No more L2 Cache -- will fix in next two weeks.

### CODE REVIEW

**Comment by hcook** [comment]
This PR injects TL2 into the tile and L1 data caches. A TL2 Broadcast hub is use to provide multi-core coherence between data caches (passes TraceGen WMO). A streamlined config library is adopted in place of cde. Icaches and RoCCs are still using TL1 behind a tilelink2.Legacy adapter.

Known API-breaking changes:
- No more BuildTiles or common Tile base class/IO. Make a custom Tile for your core, then make a Coreplex mix-in that adds some number of instances of the new Tile.
- package cde is being retired in favor of package config. Their Parameters and Config classes are API compatible but you must change the import (config offers improved functionality for Parameters and Config, but removes Knobs and Constraints). 

Known functionality regressions:
- No AXI pbus mastering (#437) -- will fix next week.
- No more cde.Knob, cde.Constraint, or cde.World -- will not fix.
- No more L2 Cache -- will fix in next two weeks.

**Comment by colinschmidt** [comment]
I assume the functionality regressions will be fixed in separate PRs so this PR will be merged sometime early next week?

**Comment by terpstra** [comment]
The AXI port will be re-added very soon. We don't plan to wait for an L2 before merging the PR.

**Comment by colinschmidt** [comment]
Thanks for the info!

**Comment by terpstra** [comment]
I just copy-pasted Henry's comment into my own so it appears at the top of the PR in case someone comes looking for what this merge was all about.

**Comment by hcook** [comment]
Both dcaches are up! Happy to have this merged when @terpstra is ready. Looks like rocket suite travis is just timing out?

**Comment by terpstra** [comment]
It has been timing out last few commits also. Might be legit? Can we
increase timeout to see?

**Comment by mwachs5** [comment]
Does this mean we now have fancy TL2 diagrams that include inside the Core?

**Comment by terpstra** [comment]
Only up to it's TL node

**Pull request merged**
