### PR TITLE
Atomics

### PR DESCRIPTION
**Pull request by terpstra**
Add atomics to TL2 and re-enable Comparator atomic testing.

### CODE REVIEW

**Comment by aswaterman** [comment]
I don't have time to CR this tonight, but since it's TL2 stuff, I'm happy to leave merging it to your discretion.

**Comment by terpstra** [comment]
It's not ready for merging just yet. The build seems to run out of RAM
again with Verilator. Also, it's turned up some sort of deadlock in the TL1
L2 cache. :-/ The TL2 port of the Comparator seems to have been working,
though.

**Comment by terpstra** [comment]
Rebased against newest master.
Now includes @hcook 's fix for Legacy not-full-beat atomics.
Now includes firrtl+verilator work-around code (Vec[Bool]=>UInt) for faster builds.

**Comment by terpstra** [comment]
It only does single-beat atomics.

**Comment by Sai-Manish** [comment]
Hello @terpstra,
I wanted to use Boom without atomics support, just disabling in the config doesn't seem to be removing the logic completely :
I have disabled this parameter : https://github.com/riscv-boom/riscv-boom/blob/3d305f2ff5dab9371d9c95754888d4b49baea556/src/main/scala/v3/common/parameters.scala#L88

Is there a better way to remove the support?
Any help would be appreciated.

**Pull request merged**
