### PR TITLE
Tl2 mmio

### PR DESCRIPTION
**Pull request by terpstra**
Refactor rocket-chip to use TL2

### CODE REVIEW

**Comment by aswaterman** [comment]
I didn't perform a detailed review, but at a glance, this is looks good.  Thanks for refactoring PRCI.

**Comment by terpstra** [comment]
My travis runs were Killed? Does this mean it ran out of memory building them?

**Comment by aswaterman** [comment]
Looks to me that GCC exhausted memory building the Verilated code.

**Comment by zhemao** [comment]
What the heck? How big of a FIRRTL file is this generating? If it's substantially larger than before, something must be wrong.

**Comment by terpstra** [comment]
Well, there are a ton of new assertions. However, the problem which caused it to run out of memory was that the PRCI was a sparse register mapped device. This has been resolved by adding an address compressor.

**Pull request merged**
