### PR TITLE
AHB-top

### PR DESCRIPTION
**Pull request by terpstra**
Support AHB buses directly out of rocket-chip.
Merge request pre-approved by Megan!

### CODE REVIEW

**Comment by aswaterman** [comment]
Can you resolve conflicts that arose with master & re-issue the PR?

**Comment by terpstra** [comment]
Gah. I'd just rebased it a half hour earlier. Done again. :-)
Please note: it depends on the chisel3 fix, as yet unreferenced by rocket-chip.

**Comment by aswaterman** [comment]
It won't merge if the regression tests don't pass, so if it depends on chisel updates, you need to include that in the PR.

**Comment by terpstra** [comment]
Alrighty. I've included the submodule commit.

**Comment by aswaterman** [comment]
@hcook @palmer-dabbelt any idea why travis isn't reporting any status for this PR?  Does it not work when the pull request comes from another user's fork, rather than a rocket-chip branch?

**Comment by colinschmidt** [comment]
Travis won't build PRs from other forks unless we enable it. Enabling that causes the double builds though. (one for the branch and one for the PR)

**Comment by xfguo** [comment]
@aswaterman I think you can try to fetch and push PR branch to ucb-bar's repo, so the CI will be start. And later you can merge the PR manually...

**Comment by aswaterman** [comment]
Good point, @xfguo.  Reopening as #125.

**Comment by aswaterman** [comment]
merged

**Pull request closed without merging**
