### PR TITLE
WIP PR to figure out why travis is failing

### PR DESCRIPTION
**Pull request by hcook**

### CODE REVIEW

**Comment by colinschmidt** [comment]
I think travis will kill any jobs longer than 50 minutes on travis.org https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

I guess we have to split up rocket suite further?

**Comment by colinschmidt** [comment]
Another thought is why are some jobs using the cache while others build them. If we fixed that we could reliably re-run the failing builds.

**Comment by colinschmidt** [comment]
Looking into this...https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

**Comment by colinschmidt** [comment]
Just read your comment on #470. I was thinking that having separate caches is not what we want, since the tools we build are usable by all builds. If you look at what caches they are fetching its clear they fetch different ones and some of them are correct. By using one cache I'm hoping that once its correct all builds will be able to succeed, but there is this danger they mention of corruption...

**Comment by hcook** [comment]
If you look under "Setting up build cache" in the log, you can see the passing ones say:
```
6.77sattempting to download cache archive
fetching travis-issues/cache-linux-precise-aa5acdf01d867f4243c7dd79e0b55d5791270f4e6bc66147f2a5c6575ffa3419--jdk-default--scala-2.10.4.tgz
found cache
```
whereas the failing ones say:
```
9.00sattempting to download cache archive
fetching travis-issues/cache-linux-precise-8f255974946400da5e81c3fb4382c8e62d686c994835ee7d40aa3eed2c1a3ca0--jdk-default--scala-2.10.4.tgz
fetching travis-issues/cache--jdk-default--scala-2.10.4.tgz
fetching master/cache-linux-precise-8f255974946400da5e81c3fb4382c8e62d686c994835ee7d40aa3eed2c1a3ca0--jdk-default--scala-2.10.4.tgz
found cache
```
and then have to build all of riscv-tools which leads them to time out.

But why one cache contains riscv-tools in regression/install whereas the other does not I cannot figure out.

**Comment by colinschmidt** [comment]
Yeah one finds a cache on this branch already (I guess because it finished the first time) and the others just get master. If we can get them to all use the same cache without corruption then we could have a no-op suite that only builds the tools for caching purposes.

**Comment by colinschmidt** [comment]
Oh goodness...we could also "warm up" the travis caches https://github.com/travis-ci/travis-ci/issues/6410

**Comment by terpstra** [comment]
We shouldn't be depending on the cache being there. The caches are intended only to speed up the build for convenience. We should not be depending on them for correctness. The reason you have SOME of the suites building with a cache is because they already succeeded once. The caches are on a per SUITE basis.

**Comment by hcook** [comment]
We're fundamentally dependent on the caches to supply riscv-gcc and have been for awhile afaict

**Comment by terpstra** [comment]
Before travis started timing out two weeks ago, caches were not working at all. That means every run rebuilt riscv-tools. Not fitting under 50 minutes is a recent regression.

**Comment by zhemao** [comment]
I'm pretty sure the jobs used to take more than 50 minutes if it couldn't find a recent cache. When did Travis start enforcing a 50 min. per-job timeout?

Since it takes around 45 min. to build riscv-tools from scratch, I don't see how we can fix this other than by ensuring that riscv-tools is pre-built.

**Comment by hcook** [comment]
Still rebuilding verilator instead of using the one in the image, but i'm merging this now to start draining the PR queue

**Pull request merged**
