### PR TITLE
pass base SCR address to SCRFile for address calculation

### PR DESCRIPTION
**Pull request by jwright6323**
This is a companion pull request to https://github.com/ucb-bar/uncore/pull/12 to generate an SCR header with correct addresses.

### CODE REVIEW

**Comment by colinschmidt** [comment]
You should bump uncore to your other pull request commit so that travis might be able to succeed. (We no longer merge commits that fail travis)

**Comment by jwright6323** [comment]
OK, it should be good to go once https://github.com/ucb-bar/uncore/pull/12 is complete.

**Comment by colinschmidt** [comment]
@jwright6323 Github is telling me you need to merge from master

**Comment by jwright6323** [comment]
@colinschmidt OK, I merged master into fixscr

**Comment by zhemao** [comment]
I have some other stuff I'm testing. I'll merge this when I'm done.

**Comment by colinschmidt** [comment]
The first commit of this was merged in at b04cd545b6fcacd51eb1aea5ec121d8409f6611a
Please submit a new PR if there are any more updates needed as github seems confused now.

**Pull request closed without merging**
