### PR TITLE
bump firrtl

### PR DESCRIPTION
**Pull request by jackkoenig**
Partially bump Firrtl. Need to wait for resolution to https://github.com/ucb-bar/firrtl/issues/511 before bumping all the way.

### CODE REVIEW

**Comment by hcook** [comment]
looks like a legit regression to me?
`Exception in thread "main" java.util.NoSuchElementException: key not found: lastGrant`
...in the InferTypes pass

**Comment by colinschmidt** [comment]
I think this is a rename thing...I ran into it in https://github.com/ucb-bar/firrtl/pull/478

**Comment by jackkoenig** [comment]
I've narrowed it to the RRArbiter:
```
circuit RRArbiter  : 
  module RRArbiter : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : {flip ready : UInt<1>, valid : UInt<1>, bits : {addr : UInt<27>}}[1], out : {flip ready : UInt<1>, valid : UInt<1>, bits : {addr : UInt<27>}}, chosen : UInt<0>}
    
    io is invalid
    io is invalid
    wire choice : UInt
    choice is invalid
    choice <= UInt<1>("h00")
    io.chosen <= choice @[Arbiter.scala 40:13]
    io.out.valid <= io.in[UInt<1>("h00")].valid @[Arbiter.scala 41:16]
    io.out.bits <- io.in[UInt<1>("h00")].bits @[Arbiter.scala 42:15]
    node _T_115 = and(io.out.ready, io.out.valid) @[Decoupled.scala 30:37]
    reg lastGrant : UInt<0>, clock @[Reg.scala 14:16]
    when _T_115 : @[Reg.scala 15:19]
      lastGrant <= io.chosen @[Reg.scala 15:23]
      skip @[Reg.scala 15:19]
    node grantMask_0 = gt(UInt<1>("h00"), lastGrant) @[Arbiter.scala 67:57]
    node validMask_0 = and(io.in[0].valid, grantMask_0) @[Arbiter.scala 68:83]
    node _T_119 = eq(validMask_0, UInt<1>("h00")) @[Arbiter.scala 31:78]
    node _T_120 = and(UInt<1>("h01"), grantMask_0) @[Arbiter.scala 72:34]
    node _T_121 = or(_T_120, _T_119) @[Arbiter.scala 72:50]
    node _T_122 = and(_T_121, io.out.ready) @[Arbiter.scala 60:21]
    io.in[0].ready <= _T_122 @[Arbiter.scala 60:16]
```

**Comment by aswaterman** [comment]
Correctly, it's a 0-width wire... but that makes me suspicious.

**Comment by jackkoenig** [comment]
Pretty sure the ZeroWidthWire pass is just missing a reference, will debug soon.

**Pull request closed without merging**
