### PR TITLE
Factor testsuite makefrag generation out of Configs and into Generator

### PR DESCRIPTION
**Pull request by hcook**

### CODE REVIEW

**Comment by zhemao** [comment]
What was the reason for getting rid of RegressionTestNames? I think that's what's causing the Travis build to fail.

**Comment by hcook** [comment]
All testsuite makefrag generation is now handled in GeneratorApp and rocketchip.Generator, instead of being threaded haphazardly through the Configs. 

- Sensible default empty make targets are provided for PROJECTs that do not contain Rocket coreplexes.
- Custom GeneratorApps are included in each client PROJECT, and launched using sbt run-main. These will output only the necessary file types.

**Comment by zhemao** [comment]
Henry, there was still one typo. I've pushed a fix for you.

**Comment by zhemao** [comment]
I'll merge once Travis passes.

**Pull request merged**
