### PR TITLE
Remove tracegen scripts, now in groundtest

### PR DESCRIPTION
**Pull request by mn416**
And bump groundtest.

### CODE REVIEW

**Comment by zhemao** [comment]
Hmm. Maybe we should have a discussion about which way is best. @aswaterman do you have any opinions one way or another?

**Comment by aswaterman** [comment]
@zhemao about whether it should be in groundtest or rocket-chip?  I putting it in groundtest is fine

**Comment by mn416** [comment]
There was some discussion at the bottom of PR #78.

The advantage of groundtest is that I have write access, so can maintain the scripts more easily.

**Comment by aswaterman** [comment]
retest this please

**Comment by aswaterman** [comment]
wait, does that work with travis?

**Comment by mn416** [comment]
From what I can tell, `.travis.yml` doesn't use these scripts so the commit shouldn't affect it. (?)

**Comment by aswaterman** [comment]
ok.  somehow we need to get it to re-run the tests if I'm to merge this commit :-)

**Comment by colinschmidt** [comment]
In travis you can look at a PR's build and click the restart build button in the upper right...But I don't even see this PR on the rocket-chip travis page. https://travis-ci.org/ucb-bar/rocket-chip/pull_requests

**Comment by colinschmidt** [comment]
Ah someone turned off build pul requests in travis. (presumably to give us more bandwidth) But this means if the PR isn't a branch of rocket-chip we can't merge them (because the tests don't run).

**Comment by colinschmidt** [comment]
The internet told me closing and re-opening would trigger a rebuild but that seems to not be the case...

**Comment by zhemao** [comment]
Okay, I'm just going to push his changes to a separate branch in our repo. Then travis can actually run on this.

**Pull request closed without merging**
