### PR TITLE
Bump FIRRTL for Sequential Memories

### PR DESCRIPTION
**Pull request by mwachs5**
This PR bumps FIRRTL to enable backend Sequential Memory descriptions.

@shunshou @yunsup I have rebased your earlier changes on top of master for this PR.

### CODE REVIEW

**Comment by zhemao** [comment]
Is this ready to go into master?

**Comment by zhemao** [comment]
We'd like this for the hurricane tapeout.

**Comment by mwachs5** [comment]
Looks like I missed one commit during the rebase, so I added that one.

**Comment by zhemao** [comment]
OK, so this is all ready to go then?

**Comment by mwachs5** [comment]
I want it now too, so good by me

**Pull request merged**
