### PR TITLE
refactor unittest framework

### PR DESCRIPTION
**Pull request by yunsup**
as a result, there's another SUITE that needs to run

### CODE REVIEW

**Comment by yunsup** [comment]
Also takes care of @aswaterman's comment on #286 regarding the unit testing framework.

**Comment by hcook** [comment]
lgtm

packages rocketchip.utest and unittest should be merged into a single package at some point but I will take care of that in a future PR.

**Comment by zhemao** [comment]
I think it would be better to keep the unit test coreplex in rocketchip. That way we don't have to override the project in the regression makefile.

**Comment by zhemao** [comment]
I guess the issue is that you still need to call the TestHarness
TestHarness.

**Pull request merged**
