### PR TITLE
Implement NASTI-based Mem/IO interconnect

### PR DESCRIPTION
**Pull request by zhemao**
These changes implement memory-mapped IO in Rocket-Chip by generating a NASTI interconnect from an address map configuration. See the individual submodule PRs for more detailed change information.

[Uncore PR](https://github.com/ucb-bar/uncore/pull/4)

[Junctions PR](https://github.com/ucb-bar/junctions/pull/3)

[Rocket PR](https://github.com/ucb-bar/rocket/pull/11)

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
@aswaterman @hcook Does this look OK?  We're going to merge Hurricane later today and I'd like to get all this in if it's going to be merged soon anyway.

**Comment by aswaterman** [comment]
I haven't had the time to look over the RTL changes to the D$, but I'll
defer to you if you think it's ready to merge.

**Comment by sbeamer** [comment]
I would figure out why bmarks failed travis first.

**Comment by colinschmidt** [comment]
The failure looks identical to the ones I've seen before, I think rerunning the build will succeed.

I'll download the log so we can diff them later assuming the rebuild succeeds.

**Pull request merged**
