### PR TITLE
rocket-chip: makes some parameters configurable.

### PR DESCRIPTION
**Pull request by zizztux**
I need to configure these parameters. And other users of rocket-chip also, I think.
- external memory base address
- number of external interrupt
- async io port

### CODE REVIEW

**Comment by zizztux** [comment]
travis-ci build result
https://travis-ci.org/zizztux/rocket-chip/builds/162664885

I don't know how upstream github system receives build result from forked repository's travis-ci.
so, I attach the link, above.

**Comment by zhemao** [comment]
Maybe @aswaterman can comment more on this, but I'm not sure we want the memory base to be a configurable parameter. It's specified in the platform spec that it must start at 0x80000000 and all of our software is written with this in mind.

I'm fine with the other changes.

**Comment by terpstra** [comment]
WithNExtInterrupts exists in current master.
I'm not sure if ExtMemBase should be configurable or not.

We need to re-add the capability to cross the AXI ports to a foreign clock domain.

**Comment by hcook** [comment]
Closing this pending further discussion in #465 and #466

**Pull request closed without merging**
