### PR TITLE
Tilelink2

### PR DESCRIPTION
**Pull request by terpstra**
This should be enough of TL2 to get us started with the conversion.

It needs more testing (e.g.: a fuzzer, a shuffler, and a RAM model monitor). However, it does appear to work and it is sufficiently featureful to begin converting slaves for the future.

### CODE REVIEW

**Comment by colinschmidt** [comment]
Is there going to be a document for upgrading?

When will things like the OuterMemorySystem be upgraded?

How long will bugfixes still be made to tilelink1?

**Comment by hcook** [comment]
> Is there going to be a document for upgrading?

Yes, there will be both a specification and an upgrade guide (these are lagging the development within the tilelink2 package so far). Also, a TL1->TL2 converter is included that will allow you to delay upgrading clients for an arbitrary length of time.

> When will things like the OuterMemorySystem be upgraded?

As early as this week for the MMIO bus. Everything else is on more of a 1+ month timeline.

> How long will bugfixes still be made to tilelink1?

I would guess for about as long as the L2 is still a TL1 implementation.

**Comment by aswaterman** [comment]
I'd like to do a code review tomorrow, but if merging this earlier will help with your productivity, go for it

**Comment by terpstra** [comment]
I welcome review, though you might need an example using it. Here's an
example:

// See LICENSE for license details.


package uncore.tilelink2


import Chisel._

import chisel3.util.LFSR16


class TLClient extends LazyModule

{

  val node = TLClientNode(TLClientParameters())


  lazy val module = new LazyModuleImp(this) {

    val io = new Bundle {

      val gpio = UInt(width = 8)

      val out = node.bundleOut

    }


    require (node.edgesOut(0).manager.beatBytes == 16)



    val addr = RegInit(UInt(0, width = 13))

    val size = RegInit(UInt(0, width = 4))

    val put = RegInit(Bool(false))

    val width = 12

    val count = RegInit(UInt(0, width = width))

    val limit = ~(SInt(-1, width=width).asUInt << size)(width-1, 0) >> 4


    val out = io.out(0)

    val edge = node.edgesOut(0)

    val data = Cat(Seq.tabulate(16) { i => UInt(i) | (count(3,0) + UInt(1))
<< 4 } .reverse)


    val (legalg, gbits) = edge.Get(UInt(0), addr, size)

    val (legalp, pbits) = edge.Put(UInt(0), addr, size, data)

    val legal = Mux(put, legalp, legalg)

    val bits = Mux(put, pbits, gbits)


    out.a.valid := legal

    out.a.bits  := bits

    out.b.ready := Bool(true)

    out.c.valid := Bool(false)

    out.d.ready := Bool(true)

    out.e.valid := Bool(false)


    when (out.a.fire()) { count := count + UInt(1) }


    when (!legal || (out.a.fire() && Mux(put, count === limit,
Bool(true)))) {

      count := UInt(0)

      size  := size + UInt(1)

      put   := LFSR16()(0)

      addr  := addr + UInt(0x100)

      when (size === UInt(8)) { size := UInt(0) }

    }

  }

}


class Bar extends LazyModule

{

  val node = TLOutputNode()


  val client = LazyModule(new TLClient)

  val xbar = LazyModule(new TLXbar)



  connect(client.node -> xbar.node)

  connect(xbar.node -> node)



  lazy val module = new LazyModuleImp(this) {

    val io = new Bundle {

      val out = node.bundleOut

    }

  }

}


class Foo extends LazyModule

{

  val ram  = LazyModule(new TLRAM(AddressSet(0, 0xfff)))

  val gpio = LazyModule(new TLGPIO(GPIOParams(7, 0x1000)))

  val xbar = LazyModule(new TLXbar)

  val bar = LazyModule(new Bar)


  connect(TLNarrower(TLHintHandler(bar.node), 16) -> xbar.node)

  connect(TLFragmenter(TLBuffer(xbar.node), 4, 256) -> ram.node)

  connect(TLBuffer(xbar.node) -> gpio.node)


  lazy val module = new LazyModuleImp(this) {

    val io = new Bundle {

    }

  }

}


object Foo extends App {

  chiselMain.run(args, () => LazyModule(new Foo).module)

}

**Comment by yunsup** [comment]
Merging this earlier would help me on splitting the Top into traits and get it ready for tilelink2 at the same time.

**Comment by mwachs5** [comment]
It helps me too with writing the peripherals.
>
>

-- 
Megan A. Wachs
Engineer | SiFive, Inc
300 Brannan St, Suite 403
San Francisco, CA  94107
megan@sifive.com

**Pull request merged**
