### PR TITLE
Make a TileLink to Smi converter availiable to users

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
See the cooresponding uncore commit for details.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
This depends on

https://github.com/ucb-bar/groundtest/pull/10
https://github.com/ucb-bar/uncore/pull/59

**Comment by palmer-dabbelt** [comment]
Something was off with the submodule hashes, probably because of the PR merge.  I rebased and changed the submodule hashes, hopefully it'll go through this time.

**Comment by aswaterman** [comment]
Yeah, it's probably because I hit the squash-and-merge button.

**Comment by palmer-dabbelt** [comment]
OK, I haven't seen that before.  It looks like even for a single-commit PR it'll rewrite stuff, which seems kind of odd.  It's fine though, now that I know this is a thing I'll just expect failures of this sort.

**Comment by aswaterman** [comment]
Yeah, it does seem odd.  Now that I know, I'll try to remember to manually rebase if the PR is against the head of master.

**Pull request merged**
