### PR TITLE
Streamline the Generator App and associated utilities. 

### PR DESCRIPTION
**Pull request by hcook**
Remove deprecated call to chiselMain and useless Chisel2 args. Update arguments to sbt run.

### CODE REVIEW

**Comment by davidbiancolin** [comment]
How do we feel about moving some of the generation utilities into CDE instead of keeping them in rocketchip? Much of this is useful outside of the context of rocketchip and it is closely coupled with the parameterization system.

**Comment by hcook** [comment]
I guess we could add some functionality to CDE to dump out files in a certain place with a certain name, but I don't really see how that would save use more than a few lines of code. The rest is pretty tightly coupled to our particular sbt run argument parsing and file naming requirements.

**Comment by davidbiancolin** [comment]
It's not so much the number of lines of code that i'm concerned about, it's the product of the number of generators and those lines. I feel like i end up implementing similar functionality across a basically all of my standalone generators. I'd assume that when SiFive has multiple chip/SoC generators, you guys might want a canonical way to elaborate and emit the design with accompanying test suites. 

In any case, this is much cleaner than what was there.

**Comment by hcook** [comment]
Yeah we are only just beginning to revamp that process; I was planning to make the rocketchip.Generator the common baseline and then specialize on top of that. Maybe it should actually become cde.Generator, but I wasn't confident enough about the standardization of what is being dumped across CDE-using projects to push it that far.

**Pull request merged**
